---
title: "Dependencies & running instructions"
author: "Me'Quvou"
date: "2025-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 6. Dependencies

**Download the right packages in terminal**

```         
pip install gspread google-auth python-dotenv selenium webdriver-manager beautifulsoup4 google-api-python-client google-auth-oauthlib google-auth-httplib2
```

**Download all packages required in Rstudio**

```         
required_packages <- c("tidyverse", "dplyr", "stringr", "lubridate", "googledrive", "dotenv", "readr", "here", "ggplot2", "tibble", "purrr", "digest")

install.packages(required_packages)
```

## 7. Running Instructions

To avoid leaking our private api keys we provide the two `..._merged.csv` files in the **zip file** and give running instructions from there on out until our final report is created.

### The Pipeline

#### 1. Clone the github repo:

-   make new directory --\> scraping_assignment
-   in this directory, clone the repo using:

```         
git clone "https://github.com/MathijsQ/oDCM_group_8"
```

#### 2. Insert raw data in correct folder

-   Create directories in /data/ : - opta AND - oddsportal
-   insert `..._merged.csv` in the corresponding folder

#### 3. In terminal run script from the "/src/scraping_html" directory:

```         
python collecting_scraping_db.py
```

#### 4. Run "standardize_teamnames.R" in R

This script takes the two `..._merged.cvs` files and creates two files correspondingly called: `..._standardized.csv`.

#### 5. Two steps in the `src/error_and_NA_insights` folders:

-   Run `missing_data_distribution.R`

    This script takes the two standardized csv's and creates a summary of missing data by competition (`match_na_by_league`) and a similar summary per match (`match_na`).

-   Run `error_distribution.R`

    This script follows the previous step and creates a plot of the distribution of the error count for opta and for oddsportal

#### 6. Run "fit_bivariate_poisson.R"

This script takes the two standardized csv's to create `bookmaker_lines_fitted.csv` and `bookmaker_fitted_params.csv`.

#### 7. Run "merging_opta_and_oddsportal.R"

This script takes the "opta_standardized.csv" and the "bookmaker_fitted_params.csv" to eventually create a merged dataset called: `results_with_params.csv`.

#### 8. Run "likelihood.R"

This script takes the "results_with_params.csv" in order to create `results_params_tail_probabilities.csv`.

#### 9. Run "formatting.R" to create the **two final datasets**

This script takes "results_params_tail_probabilities.csv" and "bookmaker_lines_fitted.csv" in order to make the final datasets called `bookmaker_vs_models_odds.csv` and `match_model_results`

#### 10. Run "final_report.Rmd" to create the **Final Report** in pdf
